server:
  address: 0.0.0.0
  port: 8080

spring:
  mvc.view.suffix: .html
  mustache.servlet.cache: false

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://database-1.c6yezxqldllc.ap-northeast-2.rds.amazonaws.com:3306/rustDB?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Seoul&autoReconnection=ture
    username: admin
    password: shrtmfdjTwh
#    url: jdbc:mysql://localhost:3306/rust?serverTimezone=Asia/Seoul
#    username: jin
#    password: Deokjin7@

  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      use-new-id-generator-mappings: false
    show-sql: false
    properties:
      hibernate:
        format_sql: true

  redis:
    host: localhost
    port: 6379

  jackson:
    serialization:
      fail-on-empty-beans: false

  mail:
    host: smtp.gmail.com
    port: 587
    username: rusttutorial@gmail.com
    password: ysuayygxdbaoucpo
    properties:
      mail:
        smtp:
          starttls:
            enable: true
            required: true
          auth: true